<?xml version="1.0" encoding="UTF-8"?>

<!--
File: usfmTex.xml
Description:
This is a component type description for a USFM Scripture component to be rendered
with TeX. All file relations and processes are described in this file.

Todo:
1) Add a process section where all processes are described
2) Add file type section that describes each kind of type of file found in the component
3) Need a section to describe project folder attributes <location>
4) Need a default component section that the system will use to create a component
5) Add a group description section

# This is a save state for this file in case we need to pull info out later.

-->

<!DOCTYPE root [
  <!ELEMENT root (section+)>
  <!ELEMENT section (name, sectionID, description, (file | folder | process | setting)+)>
  <!ELEMENT file (name, type, location, dependents, createdBy, description)>
  <!ELEMENT folder (name, key, description, value)>
  <!ELEMENT process (name, type, description)>
  <!ELEMENT setting (name, key, description, type, value)>
  <!ELEMENT key (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT dependents (#PCDATA)>
  <!ELEMENT createdBy (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT sectionID (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>

<root>
    <section>
        <name>Component Root Section</name>
        <sectionID>Components</sectionID>
        <description>This is the root section for usfmTex component information.</description>
        <section>
            <name>USFM TeX Component Information</name>
            <sectionID>usfmTex</sectionID>
            <description>This section contains general usfmTex component information.</description>
            <section>
                <name>USFM TeX Component Information</name>
                <sectionID>ComponentInfo</sectionID>
                <description>This section contains general usfmTex component information.</description>
                <setting>
                    <name>Component Type Name</name>
                    <key>componentTypeName</key>
                    <description>The name of this component type.</description>
                    <type>string</type>
                    <value>usfmTex</value>
                </setting>
                <setting>
                    <name>Valid Component ID Codes</name>
                    <key>validIdCodes</key>
                    <description>This list contains all the valid ID codes that can be used for this component type.</description>
                    <type>list</type>
                    <value>mat,mrk,luk,jhn,act,rom,1co,2co,gal,eph,php,col,1th,2th,1ti,2ti,tit,phm,heb,jas,1pe,2pe,1jn,2jn,3jn,jud,rev</value>
                </setting>
            </section>
        </section>
    </section>
</root>

